services:
  dynamodb-local:
    container_name: dynamodb-local-for-twitter-like-app
    image: amazon/dynamodb-local:1.24.0
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    volumes:
      - dynamodb-local-data:/data
    ports:
      - 8000:8000
    networks:
      - dynamodb-network

  dynamodb-admin:
    container_name: dynamodb-admin-for-twitter-like-app
    image: aaronshaf/dynamodb-admin:4.6.1
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb-local
    networks:
      - dynamodb-network

  minio:
    image: minio/minio:RELEASE.2023-10-16T04-13-43Z
    container_name: minio-for-twitter-like-app
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    entrypoint: bash
    command: -c "/opt/bin/minio server /export --address :9999 --console-address :9001"
    volumes:
      - ./minio_data:/export
    ports:
      - "9000:9999"
      - "9001:9001"
    env_file:
      - .env
    networks:
      - minio-network

volumes:
  dynamodb-local-data:

networks:
  dynamodb-network:
    driver: bridge
    external: true
  minio-network:
    driver: bridge
    external: true
