[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Riku Kurihara <kurikuribaseball530@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.34.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
